spring:
  application:
    name: dine-in-order-api

#Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/dine_in_order_db?createDatabaseIfNotExist=true
    username: root
    password: Gourab2002@Karak
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
